#!/bin/bash
echo -n "Дaтa: "
date

echo -n "Имя учетной записи: "
whoami

echo -n "Доменное имя ПК: "
hostname

echo "Процессор:"
echo -n "       Модель — "
lscpu | grep "Имя модели:" | awk '{print $3, $4, $5, $6, $7, $8}'

echo -n "       Архитектура — "
lscpu | grep "Архитектура" | awk '{print $2}'

echo -n "       Тактовая частота — "
cat /proc/cpuinfo | grep 'cpu MHz' | uniq | awk '{print $4}'

echo -n "       Количество ядер — "
cat /proc/cpuinfo | grep 'cpu cores' | uniq | awk '{print $4}'

echo -n "       Количество потоков на одно ядро — "
lscpu | grep 'Потоков на' | awk '{print $4}'


echo "Оперативная память:"
echo -n "       Всего — "
free -m | awk 'NR == 2 {print $2}'

echo -n "       Доступно — "
free -m | awk 'NR == 2 {print $4}'


echo "Жесткий диск:"
echo -n "       Всего — "
df --total --all --si | awk 'END{print $2}'

echo -n "       Доступно — "
df --total --all --si | awk 'END{print $4}'

echo -n "       Смонтировано в корневую директорию — "
df --total --all --si | awk 'END{print $5}'

echo -n "       SWAP всего — "
free -m | awk 'END{print $2}'

echo -n "       SWAP доступно — "
free -m | awk 'END{print $4}'


echo "Сетевые интерфейсы:"
count=$(ip address | grep 'qlen' | wc -l)
echo "       Количество сетевых интерфейсов — $count"
echo

for i in $(seq 1 "$count")
do
    nameDevice=$(ip address | grep 'qlen' | awk -v i=$i 'NR == i {print $2}')
    
    var=$(echo $nameDevice | grep 'NONE')
    if [[ -n $var ]]
    then continue
    fi

    echo " Имя сетевого интерфейса №$i: $nameDevice"

    macAddr=$(ip address show $nameDevice | grep 'link/' | awk '{print $2}')
    echo " MAC адрес №$i: $macAddr"

    ipAddr=$(ip address show $nameDevice | grep 'inet ' | awk '{print $2}')
    echo " IP адрес №$i: $ipAddr"

    qlen=$(ip address show $nameDevice | grep 'qlen' | awk '{print $13}')
    echo " Скорость соединения №$i: $qlen"
    echo
done